Fix issue #3 errors
Joe-McCann/cs-241-hugo-notes pull request #4
Opened 2023-01-26 15:10 UTC by jasonlewcodes

2023-01-26 15:10 UTC, Joe-McCann commented
### <span aria-hidden="true">👷</span> Deploy Preview for *joe-mccann* processing.


|  Name | Link |
|---------------------------------|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 7b63e7571ca765683f7b5c2a4e6afc539da983b7 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/joe-mccann/deploys/63d297da32d38a000853ddbf |

2023-01-30 21:17 UTC, Joe-McCann commented on content/course/introToLogic/Sections/Propositions.md
> -based on its meaning. This is all much more philisophical than our monke applied brains really care for,
monke was intentionally mispelled here per meme

2023-01-30 21:21 UTC, Joe-McCann requested changes
Revet the one `monke` change and I will approve. Great changes, I seem to misspell things a lot

2023-01-30 22:59 UTC, jasonlewcodes commented on content/course/introToLogic/Sections/Propositions.md
> -based on its meaning. This is all much more philisophical than our monke applied brains really care for,
👍

2023-01-31 03:42 UTC, Joe-McCann approved these changes
Looks good, thank you

2023-02-01 00:36 UTC, merged